config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_dmrc:
    src: dmrc
    dst: ~/.dmrc
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_wallpaper.jpg:
    src: wallpaper.jpg
    dst: ~/.wallpaper.jpg
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    chmod: '755'
  f_xsettingsd:
    src: xsettingsd
    dst: ~/.xsettingsd
    chmod: '755'
  f_zlogin:
    src: zprezto/runcoms/zlogin
    dst: ~/.zprezto/runcoms/zlogin
  f_zlogout:
    src: zprezto/runcoms/zlogout
    dst: ~/.zprezto/runcoms/zlogout
  f_zpreztorc:
    src: zprezto/runcoms/zpreztorc
    dst: ~/.zprezto/runcoms/zpreztorc
  f_zprofile:
    src: zprezto/runcoms/zprofile
    dst: ~/.zprezto/runcoms/zprofile
  f_zshenv:
    src: zprezto/runcoms/zshenv
    dst: ~/.zprezto/runcoms/zshenv
  f_zshrc:
    src: zprezto/runcoms/zshrc
    dst: ~/.zprezto/runcoms/zshrc
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_bottom:
    src: config/bottom
    dst: ~/.config/bottom
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_firefox:
    src: config/firefox
    dst: ~/.config/firefox
  d_gpicview:
    src: config/gpicview
    dst: ~/.config/gpicview
    chmod: '744'
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: '700'
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_termite:
    src: config/termite
    dst: ~/.config/termite
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
profiles:
  enzio-p6567rsrp:
    dotfiles:
    - f_bashrc
    - f_dmrc
    - f_gtkrc-2.0
    - f_p10k.zsh
    - f_wallpaper.jpg
    - f_xresources
    - f_xsettingsd
    - f_zlogin
    - f_zlogout
    - f_zpreztorc
    - f_zprofile
    - f_zshenv
    - f_zshrc
    - d_bat
    - d_bottom
    - d_dunst
    - d_firefox
    - d_gpicview
    - d_gtk-3.0
    - d_nvim
    - d_i3
    - d_polybar
    - d_rofi
    - d_termite
    - f_picom.conf
