config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_dmrc:
    src: dmrc
    dst: ~/.dmrc
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_wallpaper.jpg:
    src: wallpaper.jpg
    dst: ~/.wallpaper.jpg
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    chmod: '755'
  f_xsettingsd:
    src: xsettingsd
    dst: ~/.xsettingsd
    chmod: '755'
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_bottom:
    src: config/bottom
    dst: ~/.config/bottom
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_firefox:
    src: config/firefox
    dst: ~/.config/firefox
  d_gpicview:
    src: config/gpicview
    dst: ~/.config/gpicview
    chmod: '744'
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: '700'
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  d_bin:
    src: bin
    dst: ~/bin
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zpreztorc:
    src: zpreztorc
    dst: ~/.zpreztorc
profiles:
  enzio-p6567rsrp:
    dotfiles:
    - f_bashrc
    - f_dmrc
    - f_p10k.zsh
    - f_wallpaper.jpg
    - f_xresources
    - f_xsettingsd
    - d_bat
    - d_bottom
    - d_dunst
    - d_firefox
    - d_gpicview
    - d_gtk-3.0
    - d_nvim
    - d_i3
    - d_polybar
    - d_rofi
    - f_picom.conf
    - d_bin
    - f_starship.toml
    - d_alacritty
    - f_zshrc
    - f_zpreztorc
