# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  # source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# PATH variables
export PATH=$PATH:/home/enzio/bin/:/home/enzio/.local/bin
export PF_INFO='ascii title os host kernel uptime pkgs memory wm shell'
export FZF_DEFAULT_COMMAND='fd -H'

# Alias for Editor
alias vim='nvim'
alias vi='nvim'
export VISUAL='nvim'
export EDITOR='nvim'

# Alias for utilities
alias rm='nocorrect rm'
alias ls='exa'
alias lsa='exa -a'
alias lsla='exa -laG'
alias cat='bat --style=plain'
alias diff='diff --color'
alias dotdrop='/home/enzio/dotfiles/dotdrop.sh --cfg=/home/enzio/dotfiles/config.yaml'
alias yaydev='yay -Syu --devel --timeupdate'
alias updatenus='fluminurs --download-to ~/Documents/fluminurs --updated overwrite'

# https://github.com/romkatv/powerlevel10k/issues/888
zle-line-init() {
  emulate -L zsh
  [[ $CONTEXT == start ]] || return 0
  while true; do
    zle .recursive-edit
    local -i ret=$?
    [[ $ret == 0 && $KEYS == $'\4' ]] || break
    [[ -o ignore_eof ]] || exit 0
  done
  local saved_prompt=$PROMPT
  local saved_rprompt=$RPROMPT
  PROMPT=''
  RPROMPT=''
  zle .reset-prompt
  PROMPT=$saved_prompt
  RPROMPT=$saved_rprompt
  if (( ret )); then
    zle .send-break
  else
    zle .accept-line
  fi
  return ret
}

zle -N zle-line-init
eval "$(starship init zsh)"
bindkey -e

