env:
  TERM: alacritty

window:
  padding:
   x: 15
   y: 15
  dynamic_padding: false
  decorations: full
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 1.0

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic
  size: 9.0
  offset:
   x: 0
   y: 1

colors:
  primary:
    background: '#2e3440'
    foreground: '#c8d0e0'
  cursor:
    text: '#2e3440'
    cursor: '#d08770'
  normal:
    black:   '#3b4252'
    red:     '#bf616a'
    green:   '#a3be8c'
    yellow:  '#ebcb8b'
    blue:    '#81a1c1'
    magenta: '#b988b0'
    cyan:    '#88c0d0'
    white:   '#e5e9f0'
  bright:
    black:   '#4c566a'
    red:     '#bf616a'
    green:   '#a3be8c'
    yellow:  '#ebcb8b'
    blue:    '#81a1c1'
    magenta: '#b988b0'
    cyan:    '#8fbcbb'
    white:   '#eceff4'
  search:
    matches:
      foreground: '#81a1c1'
      background: '#4c566a'
    focused_match:
      foreground: '#ebcb8b'
      background: '#4c566a'

    colors.footer_bar:
      background: '#434c5e'
      foreground: '#88c0d0'

  hints:
    start:
      foreground: '#b988b0'
      background: '#4c566a'

    end:
      foreground: '#81a1c1'
      background: '#4c566a'

  selection:
    text: CellForeground
    background: '#3f4758'

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    blinking: Off

live_config_reload: true

mouse_bindings:
  - { mouse: Right, mods: Control, action: PasteSelection }
  - { mouse: Right, action: Copy }

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }

